### ISSUE TITLE
Changing the Font Size

### ISSUE THREAD

**Issue by Li-Yuanyuan** [costlydeveloper/ngx-awesome-popup#20]
Is it possible to make the font size configurable? Currently, it seems that I have to use both "::ng-deep" and "!important" to change the font size, eg:

```css
  ::ng-deep .text-wrapper {
    font-size: 12px !important;
  }
```
