### ISSUE TITLE
Styling does not work

### ISSUE THREAD

**Issue by mdudek** [costlydeveloper/ngx-awesome-popup#35]
I have tried to update colorlist in global config, but it does not work.

Check stackblitz: https://stackblitz.com/edit/minimal-confirm-box-s13g4b

**Comment by rmcsharry** [comment]
Same here, doesn't matter what colours I set in app.module, they do not change.

I had to add CSS to my global styles, eg:

```css
.ed-btn-customone {
  background-color: #2d922d; // slightly darker main color green, to override costlypopup CUSTOMONE
}
```
